services:
    doppy_util.temp_file_generator:
        class: Doppy\UtilBundle\TempFileGenerator\TempFileGenerator
        arguments:
            - "@doppy_util.temp_file_cleanup_listener"
            
    doppy_util.temp_file_cleanup_listener:
        class: Doppy\UtilBundle\Listener\TempFileCleanupListener
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }

    doppy_util.null_stopwatch:
        class: Doppy\UtilBundle\Stopwatch\NullStopwatch