services:
    doppy_util.temp_file_generator:
        class: Doppy\UtilBundle\TempFileGenerator\TempFileGenerator
        arguments:
            - "%doppy_util.temp_file.path%"
            - "@?doppy_util.temp_file_cleanup_listener"
