services:
    doppy_util.temp_file_cleanup_listener:
        class: Doppy\UtilBundle\Listener\TempFileCleanupListener
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }
